services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5431:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data:delegated
